---
# tasks file for security
- name: copy banner
  copy: src=banner dest=/etc/ssh/

- name: ssh config
  lineinfile:
    path: /etc/ssh/sshd_config
    line: 'Banner /etc/ssh/banner'
  notify: 
    - restartsshd
