---
version: '3'

services:
  bldr:
    build: maven-app
    volumes:
      - type: volume
        source: builddata
        target: /tmp/App42PaaS-Java-MySQL-Sample/target/

  runner:
    image: tomcat:9-alpine
    ports:
      - "8080:8080"
    links:
      - db
    volumes:
      - type: volume
        source: builddata
        target: /usr/local/tomcat/webapps/
    depends_on:
      - bldr

  db:
    image: mariadb:10.1
    ports:
      - "8514:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql:/var/lib/mysql


volumes:
  builddata:


