---
version: '3'

services:
  bldr:
    build: myapp
    volumes:
      - builddata:/tmp/App42PaaS-Java-MySQL-Sample/target/

  runner:
    build: tomcat
    ports:
      - "8080:8080"
    links:
      - db
    volumes:
      - builddata:/usr/local/tomcat/webapps/
    depends_on:
      - bldr
      - db

  db:
    image: mariadb:10.1
    ports:
      - "8514:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mariadb:/var/lib/mysql    


volumes:
  builddata:
  mariadb:


