- hosts: buildhost
  tasks:
    - name: ensure docker installed
      apt:
        name: docker.io
        state: present
    - name: copy Dockerfile
      copy:
        src: ./Dockerfile
        dest: /tmp/Dockerfile
        owner: root
        group: root
        mode: '0644'
    - name: build container image
      shell: "cd /tmp;docker build . -t hello"
    - name: archive docker image
      shell: "docker save -o /tmp/helloworld.tar hello"
    - name: download image
      fetch:
        src: /tmp/helloworld.tar
        dest: ./helloworld.tar
        flat: true
