- hosts: runhost
  tasks:
    - name: ensure docker installed
      apt:
        name: docker.io
        state: present
    - name: ensure docker installed
      apt:
        name: python-pip
        state: present
    - name: docker-py
      shell: "pip install docker-py"
    - name: upload tarball
      copy:
        src: ./helloworld.tar
        dest: /tmp/helloworld.tar

    - name: load image
      docker_image:
        name: hello
        load_path: /tmp/helloworld.tar
        state: present
        timeout: 600
    - name: run container
      docker_container:
        name: helloworld
        image: hello
        published_ports: 8080:8080
        state: started