- hosts: buildhost
  tasks:
    - name: ensure docker installed
      apt:
        name: docker.io
        state: present
    - name: copy Dockerfile
      copy:
        src: ./Dockerfile
        dest: /tmp/Dockerfile
        owner: root
        group: root
        mode: '0644'
    - name: build image
      docker_image:
        name: hello
        path: /tmp
    - name: archive docker image
      docker_image:
        name: hello
        load_path: /tmp/helloworld.tar
        state: present
    - name: download image
      fetch:
        src: /tmp/helloworld.tar
        dest: ./helloworld.tar
        flat: true
