- hosts: runhost
  tasks:
      - name: Replace
        lineinfile:
          path: /var/www/html/index.nginx-debian.html
          regexp: 'Welcome to nginx!'
          line: <p><script> document.write (new Date().toLocaleDateString()); </script></p>

