---
# tasks file for webserver

- name: install nginx
  apt: 
    name: nginx
    state: present
- name: indexhtml
  copy: src=index.html dest={{ dest_folder }}/index.html mode=0555
  notify: 
    - restartnginx
