---
version: '3'

services:
  builder:
    build: maven-app
    volumes:
      - type: volume
        source: builddata
        target: /tmp/
        volume:
          nocopy: true
  runner:
    build: tomcat-app
    volumes:
      - type: volume
        source: builddata
        target: /tmp/

volumes:
  builddata:


