---
version: '3'

services:
  bldr:
    build: maven-app
    volumes:
      - type: volume
        source: builddata
        target: /tmp/boxfuse-sample-java-war-hello/target/

  runner:
    build: tomcat-app
    volumes:
      - type: volume
        source: builddata
        target: /usr/local/tomcat/webapps/
    depends_on:
      - bldr


volumes:
  builddata:



