---
version: '3'

services:
  builder:
    build: maven-app
    volumes:
      - builddata:/tmp/builddata

  runner:
    build: tomcat-app
    volumes:
       - builddata:/tmp/builddata
       volume:
         nocopy: true
volumes:
  builddata:


