---
version: '3'

services:
  builder:
    build: maven-app
    volumes:
      - type: volume
        source: builddata
        target: /tmp/builddata

  runner:
    build: tomcat-app
    volumes:
      - type: volume
        source: builddata
        target: /tmp/builddata
volumes:
  builddata:


