---
version: "3"

services:
  builder:
    build: maven-app
    volumes:
      - type: volume
        source: builddata
        target: /builddata

  runner:
    build: tomcat-app
    volumes:
      - type: volume
        source: builddata
        target: /builddata
volumes:
  builddata:


