---
version: "3"
services:
  builder:
    build: maven-app
    volumes:
      - build:/tmp
  runner:
    build: tomcat-app
    volumes:
      - build:/tmp
    volumes_from:
      - builder
volumes:
  build:
