---
version: '3.7'

services:
  builder:
    build: maven-app
    volumes:
      - /tmp
      - type: volume
        source: builddata
        target: /tmp/

  runner:
    build: tomcat-app
    volumes:
      - /tmp
      - type: volume
        source: builddata
        target: /tmp/

volumes:
  builddata:
    name: builddata


