---
version: '3'

services:
  builder:
    build: maven-app
    volumes:
      - type: bind
        source: /tmp
        target: /tmp/builddata

  runner:
    build: tomcat-app
    volumes:
      - type: bind
        source: /tmp
        target: /tmp/builddata

