---
version: '3'

services:
  bldr:
    build: maven-app
    volumes:
      - type: volume
        source: builddata
        target: /tmp/

  runner:
    build: tomcat-app
    volumes:
      - type: volume
        source: builddata
        target: /tmp/
    depends_on:
      - blrd


volumes:
  builddata:



