---
version: "3"
volumes:
  builddata:
    external: true

services:
  builder:
    build: maven-app
    volumes:
      - builddata:/tmp/
  runner:
    build: tomcat-app
    volumes_from:
      - builder
