---
version: "3"
services:
  builder:
    build: maven-app
    volumes:
      - /tmp/:/tmp/
    volumes_from:
      - runner
  runner:
    build: tomcat-app
    volumes:
      - /tmp/:/tmp/
    volumes_from:
      - builder
