---
version: "3"
services:
  builder:
    build: maven-app
    volumes:
      - bld:/tmp/build
  runner:
    build: tomcat-app
    volumes:
      - bld:/tmp
    volumes_from:
      - builder
volumes:
  bld:
