---
# tasks file for docker
- name: ensure docker installed
  apt:
    name: docker.io
    state: present
- name: ensure docker installed
  apt:
    name: python-pip
    state: present
- name: docker-py
  pip:
    name: docker-py
    state: present
- name: send image
  copy:
    src: {{ host_img_dump }}
    dest: {{ img_dump }}

- name: load image
  docker_image:
    name: hello
    load_path: {{ img_dump }}
    state: present
    timeout: 600
- name: run container
  docker_container:
    name: helloworld
    image: hello
    ports:
      - "8080:8080"
